OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: IdentityAuthority
    Domain: identityauthority.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Bank
    Domain: bank.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Telecom
    Domain: telecom.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
